global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'serengeti'
    static_configs:
      - targets: ['serengeti-primary:1985', 'serengeti-secondary:1985']
        labels:
          group: 'serengeti-cluster'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']